from __future__ import annotations

ALIBABA_PLATFORM_ID = "alibaba"
PYTHINKER_CODE_PLATFORM_ID = "pythinker-code"
OPENAI_API_PLATFORM_ID = "openai"
OPENAI_CHATGPT_PLATFORM_ID = "openai-chatgpt"
OPENCODE_GO_PLATFORM_ID = "opencode-go"
MINIMAX_PLATFORM_ID = "minimax"
MOONSHOT_PLATFORM_ID = "moonshot"
KIMI_PLATFORM_ID = "kimi"
DEEPSEEK_PLATFORM_ID = "deepseek"
ANTHROPIC_PLATFORM_ID = "anthropic"
OPENROUTER_PLATFORM_ID = "openrouter"
LM_STUDIO_PLATFORM_ID = "lm-studio"
OLLAMA_PLATFORM_ID = "ollama"
ZAI_PLATFORM_ID = "z-ai"

__all__ = [
    "ALIBABA_PLATFORM_ID",
    "ANTHROPIC_PLATFORM_ID",
    "DEEPSEEK_PLATFORM_ID",
    "KIMI_PLATFORM_ID",
    "LM_STUDIO_PLATFORM_ID",
    "MINIMAX_PLATFORM_ID",
    "MOONSHOT_PLATFORM_ID",
    "OLLAMA_PLATFORM_ID",
    "OPENAI_API_PLATFORM_ID",
    "OPENAI_CHATGPT_PLATFORM_ID",
    "OPENCODE_GO_PLATFORM_ID",
    "OPENROUTER_PLATFORM_ID",
    "PYTHINKER_CODE_PLATFORM_ID",
    "ZAI_PLATFORM_ID",
]
